/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.Course;
import Backend.CourseService;
import Backend.Student;
import Backend.UserService;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.FileReader;
import java.io.BufferedReader;
import java.util.ArrayList;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author hp
 */
public class StudentEnrolled extends javax.swing.JFrame {
    private Student student;
    private UserService userService;
    private CourseService courseService;

    /**
     * Creates new form StudentEnrolled
     */
    public StudentEnrolled(Student student) {
        initComponents();
        this.student=student;
        userService = new UserService();
        courseService= new CourseService();
        loadCourses();
        this.setLocationRelativeTo(null);
        
    }

   /* private void loadCourses() {
        ArrayList<String> courses = userService.displayEnrolledCourses(student.getUserId());
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Course Id", "Course Name", "Progress"});
        jTable1.setModel(model);

        for (String cId : courses) {
            Course course = courseService.getCourseById(cId);
            if (course != null) {

                ArrayList<String> completedLessons = new ArrayList<>();
                for (Backend.StudentCourseProgress p : student.getCoursesProgress()) {
                    if (p.getCourseId().equals(cId)) {
                        completedLessons = p.getCompletedLessons();
                        break;
                    }
                }


                int totalLessons = course.getLessons().size();
                int completedCount = completedLessons.size();
                String progress = totalLessons > 0 ? (completedCount * 100 / totalLessons) + "%" : "0%";


                model.addRow(new Object[]{
                        course.getCourseId(),
                        course.getCourseName(),
                        progress
                });
            }
        }

        jTable1.setModel(model);
    }*/
   private void loadCourses() {
       ArrayList<String> courses = userService.displayEnrolledCourses(student.getUserId());
       DefaultTableModel model = new DefaultTableModel();
       model.setColumnIdentifiers(new String[]{"Course Id", "Course Name", "Progress"});
       jTable1.setModel(model);

       for (String cId : courses) {
           Course course = courseService.getCourseById(cId);
           if (course != null) {
               int totalLessons = course.getLessons().size();
               int progress = student.getProgressPercentage(cId, totalLessons);
               String progressStr = progress + "%";

               model.addRow(new Object[]{
                       course.getCourseId(),
                       course.getCourseName(),
                       progressStr
               });
           }
       }
   }



    private void openSelectedCourseLessons() {
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Select a course!");
        return;
    }

    String courseId = jTable1.getValueAt(selectedRow, 0).toString();
    String courseName = jTable1.getValueAt(selectedRow, 1).toString();

    ViewLessons vl = new ViewLessons(student, courseId);
    vl.setTitle("Lessons for: " + courseName);
    vl.setVisible(true);
    this.setVisible(false);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        ViewLessons = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("    Student enrolled courses");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Id", "Course Name", "Progress"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Go back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ViewLessons.setText("View Lessons");
        ViewLessons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewLessonsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewLessons))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewLessons)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      /* Login l = new Login();
        l.setVisible(true);*/
      StudentDashBoard sb = new StudentDashBoard(student);
      sb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ViewLessonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewLessonsActionPerformed
        // TODO add your handling code here:
        openSelectedCourseLessons();
    }//GEN-LAST:event_ViewLessonsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentEnrolled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentEnrolled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentEnrolled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentEnrolled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new StudentEnrolled().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewLessons;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
